[package]
name = "test-xrepo-ref"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "crates/mylib",
]

[dependencies]
mylib = { path = "crates/mylib" }
